requestName : workshop-test
productionType : multiply-iterative
simulation : True
data_root : /Data/m1/

General:
    roi: POLYGON((-2.20397502663252 39.09868106889479,-1.9142106223355313 39.09868106889479, -1.9142106223355313 38.94504502508093,-2.20397502663252 38.94504502508093, -2.20397502663252 39.09868106889479))
    start_time: 2017-01-01
    end_time: 2017-01-20
    time_interval: 10 #days
    spatial_resolution: 60 # metres
    state_mask: .Barrax_pivots.tif
    output_directory_root: /Data/m1/
    # output_prefix: my_test_33

Inference: # inference config
    parameters:
        - n
        - cab
        - car
        - cbrown
        - cw
        - cm
        - lai
        - ala
        - bsoil
        - psoil
    optical_operator_library: some_operator.nc   # Optional
    sar_operator_library: some_other_operator.nc # Optional
    a: identity
    inflation: 1e3
    time_interval: 10 # 1 day

Prior:
# Prior section conventions

# - 1. sub-level contains all potential variables (sm, roughness, lai, ..)
#   which are asked for/being inferred from Orchestrator/Inferrence Engine
#   and for which prior information is provided.
# - 2. sub-level contains prior type (ptype). These can be commented out
#   to be omitted.

  General:
#    directory_data:  /software/prior-engine-0.5/aux_data/Static/Vegetation/
     directory_data: /data/auxiliary/priors/Static/Vegetation/
#     directory_data: /data/m5/
  sm:
    climatology:
       climatology_dir: /data/auxiliary/priors/Climatology/SoilMoisture/
    #  climatology_dir: /software/prior-engine-0.5/aux_data/Climatology/SoilMoisture/
    #  climatology_dir: ./aux_data/Climatology/SoilMoisture/
    # munich:
    #  dir: ./aux_data/munich/SoilMoisture/
    # dynamic:
    #     type: dynamic
    #     model:
    #         - API
    #         - other
    # recent:
    #   aux_data = ...
    # static:
    #       type: static
  lai:
    database:
        static_dir: 'same as General directory_data'
  cab:
    database:
        static_dir: 'same as General directory_data'
  car:
    database:
        static_dir: 'same as General directory_data'
  cw:
    database:
        static_dir: 'same as General directory_data'
  cdm:
    database:
        static_dir: 'same as General directory_data'
  n:
    database:
        static_dir: 'same as General directory_data'
  cbrown:
    database:
        static_dir: ''
  cm:
    database:
        static_dir: ''
  ala:
    database:
        static_dir: ''
  bsoil:
    database:
        static_dir: ''
  psoil:
    database:
        static_dir: ''

    #climatology:
    #  database: ../aux_data/new_geotiff
    # model:
  # veg:
    # veg_pft:
    #   type: pft
    #   database: /aux_data/some_DB
    # veg_spec:
    #   type: species
    #   database: /user_data/some_DB
    # -

